import time

# Move: Lean Back

# Pick up back feet
move('Stand')



hexy.RF.knee(0)
hexy.RF.ankle(0)
time.sleep(.5)
move('Stand')
hexy.RB.knee(0)
hexy.RB.ankle(0)
time.sleep(.5)
move('Stand')
hexy.LB.knee(0)
hexy.LB.ankle(0)
time.sleep(.5)
move('Stand')
hexy.LF.knee(0)
hexy.LF.ankle(0)
time.sleep(.5)
move('Stand')
hexy.RF.knee(0)
hexy.RF.ankle(0)
hexy.LB.knee(0)
hexy.LB.ankle(0)
time.sleep(.5)
move('Stand')
hexy.LF.knee(0)
hexy.LF.ankle(0)
hexy.RB.knee(0)
hexy.RB.ankle(0)
time.sleep(.5)
move('Stand')

hexy.RF.knee(0)
hexy.RF.ankle(0)
hexy.LF.knee(0)
hexy.LF.ankle(0)
hexy.RB.knee(0)
hexy.RB.ankle(0)
hexy.LB.knee(0)
hexy.LB.ankle(0)
time.sleep(1.5)
move('Stand')
hexy.RF.knee(0)
hexy.RF.ankle(0)
time.sleep(.5)
hexy.RF.knee(70)
time.sleep(.5)
hexy.RF.knee(-75)
time.sleep(.5)
hexy.RF.knee(70)
time.sleep(.5)
hexy.RF.knee(-75)
time.sleep(.5)
hexy.RF.knee(70)
time.sleep(.5)
hexy.RF.knee(-75)
time.sleep(.5)
move('Stand')
