import time
move('Stand')
time.sleep(.2)

for i in range(2):
    move('MoveForward')
    time.sleep(.5)
    move('MoveLeft')
    time.sleep(.5)
    move('MoveLeft')
    time.sleep(.5)
    move('MoveBackward')
    time.sleep(.5)
    move('MoveRight')
    time.sleep(.5)
    move('MoveRight')
    time.sleep(.5)
    move('Clap')
    time.sleep(.2)
    move('RotateRight')
    time.sleep(.5)
    move('RotateRight')
    time.sleep(.5)
    move('RotateRight')
    time.sleep(.5)
move('Stand')
move('Panic')
